### PR TITLE
Fix synced folder name with Windows paths

### LINKED ISSUE #9: Synced folder targets
Synced folders do not appear to be generating the correct path when creating endpoint name on Windows guests. Configuration in use and behavior is described here: https://discuss.hashicorp.com/t/vmware-non-default-synced-folders-are-provided-with-incorrect-target/26851

### PR DESCRIPTION
**Pull request by chrisroberts**
Removes more special characters from the guest path when
creating the synced folder named used for sharing within
the guest. This prevents encoded characters from being
introduced into the name and breaking the generated link.

Fixes #9

### CODE REVIEW

File: lib/vagrant-vmware-desktop/driver/base.rb [hunk 1]
```diff
@@ -398,7 +398,11 @@ def create_vmnet_device(config)
         # This deletes the VM.
         def delete
           @logger.info("Deleting VM: #{@vm_dir}")
-          @vm_dir.rmtree
+          begin
+            @vm_dir.rmtree
+          rescue Errno::ENOTEMPTY
+            FileUtils.rm_rf(@vm_dir.to_s)
```
Comment (soapy1) [inline lib/vagrant-vmware-desktop/driver/base.rb:404]: Why not always `FileUtils.rm_rf(@vm_dir.to_s)` instead of trying `@vm_dir.rmtree` and falling back to using FileUtils?

**Review by soapy1 — APPROVED** [review]

File: lib/vagrant-vmware-desktop/driver/base.rb (hunk 1 above)
Comment (chrisroberts) [reply lib/vagrant-vmware-desktop/driver/base.rb:404]: Mainly just to retain existing behavior, since it rarely happens :shrug:
